# Generated by Django 5.1.2 on 2024-10-13 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_tag_child_alter_tag_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='child',
        ),
        migrations.AlterField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.tag'),
        ),
    ]
