# Generated by Django 5.1.2 on 2024-10-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_tag_child_alter_tag_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readquestion',
            name='user',
        ),
    ]
