version: '3.3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'question_system'
      MYSQL_USER: 'question_system'
      MYSQL_PASSWORD: 'question_system'
      MYSQL_ROOT_PASSWORD: 'question_system'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  app:
    build: .
    restart: always
    environment:
      DB_NAME: 'question_system'
      DB_USER: 'question_system'
      DB_PASSWORD: 'question_system'
      DB_HOST: 'db'
      DB_PORT: '3306'
    ports:
      - '8000:8000'
    depends_on:
      - db  
    volumes:
      - .:/app 

    
volumes:
  my-db: